apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
  - protocol: TCP
    port: 80        # service port
    targetPort: 8080  # container port
  type: NodePort
